logging:
  level:
    com.bank.notifications: DEBUG

spring:
  cloud:
    zookeeper:
      connect-string: ${ZOOKEEPER_CONNECT_STRING:localhost:2181}
      discovery:
        enabled: true
        register: true

server:
  port: 8084